### ISSUE TITLE
Add support for iosSimulatorArm64 target

### ISSUE THREAD

**Issue by GrahamBorland** [arkivanov/MVIKotlin#1]
Please consider adding support for the `iosSimulatorArm64` target.

This currently fails due to the issue described in https://github.com/badoo/MVIKotlin/issues/200

**Comment by arkivanov** [comment]
Hello @GrahamBorland , `iosSimulatorArm64` is supported starting from version `3.0.0-alpha02`. Would this be ok?

**Comment by GrahamBorland** [comment]
OK, I'll give the alpha a try, thanks.

**Comment by arkivanov** [comment]
Closing this issue for now, feel free to reopen if there are any problems.
