### ISSUE TITLE
Support wasmJs target

### ISSUE THREAD

**Issue by ghost** [arkivanov/MVIKotlin#120]
Can you share your thougts can it be implemented?
Thanks

**Comment by arkivanov** [comment]
Do you mean the `wasmJs` target? I don't think MVIKotlin is related to Compose Multiplatform.

**Comment by ghost** [comment]
@arkivanov yes

**Comment by arkivanov** [comment]
Thanks, this is indeed planned. Currently blocked by stable versions of Reaktive and kotlinx-coroutines with Wasm support. Basically waiting for kotlinx-coroutines 1.8.0.

**Comment by arkivanov** [comment]
Reaktive and Coroutines now support Wasm, we can now add the support to MVIKotlin. I will work on it soon.
