### ISSUE TITLE
Executors CoroutineScope with new store DSL API

### ISSUE THREAD

**Issue by SuLG-ik** [arkivanov/MVIKotlin#127]
Now only CoroutineExecutorScope is CoroutineScope. But sometimes you need to use CoroutineScope to perform operations outside of onIntent/onAction. The old API gives access to the scope and it is possible to use it both after receiving the intent/action and independently.  For example, to execute a mutable queue through another object and wait for the execution state already in onIntent/onAction.
I suggest give access for executor's CoroutineScope in ExecutorBuilder outside onIntent/onAction or another mechanism that allows you to implement the above behavior

**Comment by arkivanov** [comment]
Sorry for the delay, for some reason I missed the notification about this issue.

Could you please elaborate, where else do you need the access to `CoroutineExecutorScope` outside of `onIntent` and `onAction`? Maybe provide an code snippet?

**Comment by arkivanov** [comment]
Maybe something like [this](https://github.com/arkivanov/MVIKotlin/blob/ce593079517004289f9c3ee3e6161091e9f595a0/sample/coroutines/shared/src/commonMain/kotlin/com/arkivanov/mvikotlin/sample/coroutines/shared/details/store/DetailsStoreFactory.kt#L32) would help?

**Comment by SuLG-ik** [comment]
This solution helps with run something where CoroutineScope exists - CoroutineExecutorScope in onIntent/onAction handlers. 
I find bad solution is creating coroutine scope out of executor creation dsl, give it into some service that should be connected with store's lifecycle, and manual dismiss created coroutine scope in store's dismiss.

**Comment by arkivanov** [comment]
Sorry, but I still don't understand the problem. Maybe you could provide an example?

**Comment by arkivanov** [comment]
Closing this for now. Feel free to reopen with an example code.
