### ISSUE TITLE
Another supplier is already registered with the key

### ISSUE THREAD

**Issue by nevrozza** [arkivanov/MVIKotlin#140]
Hi! I'm trying to add State preservation by saving state of a store (like in sample):
```
fun create(stateKeeper: StateKeeper): UsersStore =
        object :
        UsersStore,
        Store<Intent, State, Label> by storeFactory.create(
            name = "UsersStore",
            initialState = stateKeeper.consume(
                key = "UsersStoreState",
                strategy = State.serializer()
            ) ?: UsersStore.State(),
            executorFactory = {
                UsersExecutor(
                    adminRepository = adminRepository,
                    nUsersInterface = nUsersInterface,
                    eUserBottomSheet = eUserBottomSheet,
                    cUserBottomSheet = cUserBottomSheet
                )
            },
            reducer = UsersReducer
        ) {}.also {
            stateKeeper.register("UsersStoreState", strategy = State.serializer()) {
                it.state
            }
        }
```

And it works but when i close app or restart this component i get next error: `Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Another supplier is already registered with the key: UsersStoreState`

I understand why it happens but idk how to fix it in the best way....
Thanks!

**Comment by arkivanov** [comment]
Well, without a reproducer it's hard to say. Obviously the `register` function is being called twice on the same instance of `StateKeeper` with the same key, which is prohibited. Make sure you are not passing the parent `ComponentContext` to a child component, see: https://arkivanov.github.io/Decompose/faq/#error-another-supplier-is-already-registered-with-the-key.

**Comment by nevrozza** [comment]
> Make sure you are not passing the parent `ComponentContext` to a child component

@arkivanov, thanks for your reply! 
But if I'm not using parent componentContext (I used parent stateKeeper but it crashed), I have a new stateKeeper all the time, which makes it impossible to get the old state..

**Comment by arkivanov** [comment]
It would be nice to see some code or a reproducer.

**Comment by nevrozza** [comment]
@arkivanov
[Here is the repository (folder)](https://github.com/nevrozza/PansionApp/tree/main/common/admin/presentation/src/commonMain/kotlin/users) where I tried to save the store in UsersStoreFactory.kt.

PS: There can be a lot of bad code here: I'm still a beginner

**Comment by arkivanov** [comment]
I couldn't reproduce the issue, it would be nice if you could provide exact steps to reproduce.

One thing that I noticed is that you are incorrectly saving and restoring the state of the Store. Please see the [docs](UsersStoreState), specifically the examples "Saving state of a retained instance".

**Comment by nevrozza** [comment]
@arkivanov 
This works if I pass InstanceKeeper and stateKeeper (for saving state in saved_state.dat) from RootComponent to UsersStoreComponent....
Like:
```
class UsersComponent(
    componentContext: ComponentContext,
    storeFactory: StoreFactory,
    private val stKeeper: StateKeeper,
    private val inKeeper: InstanceKeeper,
    private val output: (Output) -> Unit
) : ComponentContext by componentContext {
    private val usersStore =
        inKeeper.getStore {
            UsersStoreFactory(
                storeFactory = storeFactory,
                adminRepository = adminRepository,
                nUsersInterface = nUsersInterface,
                eUserBottomSheet = eUserBottomSheet,
                cUserBottomSheet = cUserBottomSheet
            ).create(stKeeper)
        }
}
```
```
fun create(stateKeeper: StateKeeper): UsersStore =
        object :
        UsersStore,
        Store<Intent, State, Label> by storeFactory.create(
            name = "UsersStore",
            initialState = stateKeeper.consume(
                key = "USERS_STORE_STATE",
                strategy = State.serializer()
            ) ?: UsersStore.State(),
            executorFactory = {
                UsersExecutor(
                    adminRepository = adminRepository,
                    nUsersInterface = nUsersInterface,
                    eUserBottomSheet = eUserBottomSheet,
                    cUserBottomSheet = cUserBottomSheet
                )
            },
            reducer = UsersReducer
        ) {}.also {
            stateKeeper.register("USERS_STORE_STATE", strategy = State.serializer(), supplier = it::state)
        }
```

I can instead use stKeeper and inKeeper, but override stateKeeper and instanceKeeper (UsersComponent parameters). Is this acceptable, or can it lead to Undefined behaviour?

**Comment by arkivanov** [comment]
No, that's not ok. You should always use things from the component's component context.

And as I mentioned earlier, you shouldn't call `register` from inside `getStore {}`. The following case won't work:

1. Open the component.
2. Rotate the screen.
3. Change the store state.
4. Minimize the app.
5. Simulate process death by calling `adb shell am kill <package_name>`
6. Open the app and observe the state is not restored.

Please refer to the docs I linked earlier.

**Comment by nevrozza** [comment]
@arkivanov 
I noticed that the childContext is always different (close - open the screen). Is this how it should be?

**Comment by arkivanov** [comment]
What you mean by "different"? Could you please elaborate?

**Comment by nevrozza** [comment]
first screen opening:
com.arkivanov.essenty.instancekeeper.DefaultInstanceKeeperDispatcher@523c05e3
second screen opening:
com.arkivanov.essenty.instancekeeper.DefaultInstanceKeeperDispatcher@55428b9

it's from:
```
init {
   println(instanceKeeper)
}
```

UPD: Ok, I checked something and realized that wasn't the problem

**Comment by nevrozza** [comment]
Ok, I'm just idiot. When the program was launched, a function(gotoHome()) was triggered that cleared the entire stack, i.e. killed all components

**Comment by arkivanov** [comment]
No problem!
