### ISSUE TITLE
todo-app-android and todo-app-ios dirs should be removed?

### ISSUE THREAD

**Issue by treitter** [arkivanov/MVIKotlin#42]
It seems the directories `sample/todo-app-{android,ios}` were effectively split up between the coroutines and reaktive versions but a few files are left in the old locations.

Most notably, I updated my git checkout and tried to load `sample/todo-app-ios/todo-app-ios.xcodeproj` unsuccessfully because its dependencies are now missing.

**Comment by arkivanov** [comment]
Those directories are no longer present in the repository, as you can see here: https://github.com/arkivanov/MVIKotlin/tree/master/sample

As you mentioned, folders `sample/todo-app-{android,ios}` were moved under `sample/coroutines` and `sample/reaktive`.

**Comment by treitter** [comment]
Ah, you're right. Git noted them being untracked so a `git clean -xdf` removed them. I guess it refused to delete (untracked) `build` directories and the Xcode project file was probably retained because I had Xcode open at the time.

Thanks for confirming!
