### ISSUE TITLE
Time Travel app missing dependency

### ISSUE THREAD

**Issue by DSeeLP** [arkivanov/MVIKotlin#48]
Since compose-jb 1.1.1 `kotlinx-coroutines-swing` is no longer included. This leads to an error when clicking `Connect to application`.

**Comment by arkivanov** [comment]
Oh no! Thanks for reporting, I will fix!

**Comment by arkivanov** [comment]
Thanks for fixing the issue! I have updated artifacts for Linux and Windows in the latest [v3.0.0](https://github.com/arkivanov/MVIKotlin/releases/tag/3.0.0) release.
