### ISSUE TITLE
Update time travel docs

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/MVIKotlin#54]
The plugin functionality is actually similar to the desktop client app, it can connect to Android, JVM and Darwin apps. Also there are typos, e.g. "All recording events will appear ...".
Link: https://arkivanov.github.io/MVIKotlin/time_travel.html

**Comment by Gilbert1817** [comment]
Pls help,and guide me to fill-up for the guidelines.

**Comment by arkivanov** [comment]
The source file is here: https://github.com/arkivanov/MVIKotlin/blob/master/docs/time_travel.md

There are the following mistakes:

- The section [Using time travel clients](https://github.com/arkivanov/MVIKotlin/blob/master/docs/time_travel.md#using-time-travel-clients) mentions only Android for the IntelliJ IDEA plugin, however it should be same as for the standalone desktop client. So both sections should be updated to nicely reflect the thing.
-  There is a typo in the doc page - "All recording events will appear ...", I guess it should be "All recorded events will appear ...".
