### ISSUE TITLE
Current support status for tvos target

### ISSUE THREAD

**Issue by denislfernandez** [arkivanov/MVIKotlin#65]
Hello  @arkivanov ,

First of all I want to congratulate and thank you for all the hard work you put on this library. I've been using it the past few months with a multiplatform app that runs on JS, Android and iOS and I am really happy with the results so thanks so much for your contribution to the community!

I was hoping to add tvos support to the application I was wandering what is the current support for the tvos target. I've seen that no artifacts are published to maven repository but checking the code of the repository and the code of the com.arkivanov.gradle.setup plugin that the tvos target is not configured by default but there are some bits of code indicating that may be configured (I've not checked the code deeply but I have seen the posibility of adding the targets through the tvosCompat() function of the plugin). Could I fork the project and try to setup the support the tvos locally and expect it to work or is disabled by default due to some other reason?

Thank you again for your time and work!

**Comment by arkivanov** [comment]
Hello and thank you for the feedback! MVIKotlin doesn't support tvos for now. There should be just one line added [here](https://github.com/arkivanov/MVIKotlin/blob/8d06462eff0225a99111633cc99f024f8de2b52f/build.gradle.kts#L32) - `tvosCompat`. I believe after that the project should compile just fine and all tests should pass.

I will appreciate your help here.
