### ISSUE TITLE
Allow .exe files in Time Travel ADB file picker

### ISSUE THREAD

**Issue by Danzolax** [arkivanov/MVIKotlin#70]
When selecting the location of adb in the time-travel plugin, there is no possibility to select a file with the .exe extension.
![image](https://user-images.githubusercontent.com/56091783/193534495-359cb0b1-9792-481f-873a-38ce75de633c.png)

**Comment by arkivanov** [comment]
1. [selectAdbPath](https://github.com/arkivanov/MVIKotlin/blob/ae716edd787ce657b84c8cb5987d6bb3e77ff8be/mvikotlin-timetravel-client/app-desktop/src/jvmMain/kotlin/com/arkivanov/mvikotlin/timetravel/client/desktop/Main.kt#L143) function in the desktop app.
2. [selectAdbPath](https://github.com/arkivanov/MVIKotlin/blob/a7bc4041b2493cd7fc8a289cc3da4097b54a9bc1/mvikotlin-timetravel-client/plugin-idea/src/main/java/com/arkivanov/mvikotlin/plugin/idea/timetravel/TimeTravelToolWindow.kt#L131) function in the IDEA plugin.
