### ISSUE TITLE
After making this repo as fork, search in the repository doesn't work

### ISSUE THREAD

**Issue by ultraon** [arkivanov/MVIKotlin#8]
**Not related to the library itself, but would be nice to have it as an issue.**

Hello @arkivanov , I've noticed that search in the repo doesn't work anymore.
Even tried with suggested approach, still no success:
https://docs.github.com/en/search-github/searching-on-github/searching-in-forks

I tried this request also:
https://github.com/search?q=isAssertOnMainThreadEnabled+repo%3Aarkivanov%2FMVIKotlin+fork%3Atrue

Who knows how to search on the forked repository?

**Comment by arkivanov** [comment]
Yes unfortunately this is true, I mentioned this limitation in the readme. There are two ways of fixing this:

1. Make this repository more stars than upstream
2. Try to unfork the repository, probably by asking GitHub support

The community can definitely help with the first point. And I will try the second option once this repository diverge significantly enough.

Thanks for raising the issue, let's keep it open for transparency.

**Comment by arkivanov** [comment]
The repository was detached from the parent, the code search now works! Thanks for all your support! ♥️
