### ISSUE TITLE
Logger interface should be a fun interface

### ISSUE THREAD

**Issue by dalewking** [arkivanov/MVIKotlin#82]
Logger interface has one method so it should be declared a fun interface so that it can be implemented using a lambda.

**Comment by arkivanov** [comment]
Makes sense, thanks.

**Comment by arkivanov** [comment]
Sorry, but I had to revert this change. Those interfaces are likely to get more methods in the future.

Consider the following kind of helpers for your needs:

```kotlin
fun Logger(log: (String) -> Unit): Logger =
    object : Logger {
        override fun log(text: String) {
            log.invoke(text)
        }
    }
```
