### ISSUE TITLE
New ExecutorBuilder implementation makes it difficult to share logic

### ISSUE THREAD

**Issue by dalewking** [arkivanov/MVIKotlin#93]
So the case is that you have 2 intents or actions that have to do basically the same stuff so need to share a lot of code that needs to have access to state and be able to dispatch messages of publish labels. Under the old Executor class that was easy because you could extract the common code into a function inside the Executor as it had access to the state, publish and dispose functions. defined in the Executor.

But when you move to ExecutorBuilder there isn't a good way to extract that logic to a function inside the ExecutorBuilder. Those functions will live inside ExecutorBuilder not the executor itself.

**Comment by arkivanov** [comment]
Yes, there is a trade-off. If your Store is simple and there is not much to share, you can use the DSL. But in more complex cases it is advised to extend `Executor` as usual. Though, you can put your `Executor` implementation at top level, instead of placing it inside a `MyStoreFactory` class.
